# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Fast, branch-centric git worktree manager"
  homepage "https://github.com/trungung/wt"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trungung/wt/releases/download/v0.0.5/wt_Darwin_x86_64.tar.gz"
      sha256 "8e7465d36f0132ad8e3ced84c48f6d7f4ee2104045682f3143ea3ff0500ad213"

      def install
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trungung/wt/releases/download/v0.0.5/wt_Darwin_arm64.tar.gz"
      sha256 "3528565da4bf7a93b80fdfa49cb80636fca10138b7db8d4ee02398d9a602063c"

      def install
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trungung/wt/releases/download/v0.0.5/wt_Linux_x86_64.tar.gz"
      sha256 "b0793d181e4793ac9256846ef1ae2c4f03abee2af09956ab9a3504fcababd331"
      def install
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trungung/wt/releases/download/v0.0.5/wt_Linux_arm64.tar.gz"
      sha256 "2fcf6d07cd577e76da04e5f2283e83e6d9ff903ef8a3c6ab133b208ecd5b4719"
      def install
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
